# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc5c8086ddf5fc85da79dd890922a291456e936b752e1809659f8cff5b26a12358941bb90dacf99c9905322a5b41956cf050d332488b580f11e3398eebea5afc

test:
  secret_key_base: 27058244f1b7c1349354d282d6d23c4fbb824a26b2def7be9ee05959f00269df473d1196c5f134624b65218fbc4c249d51b1ab32c1370f0716c183ff96d10122

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
